version: '3.8'
services:
  config-server:
    build:
      context: ../config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - C:/Users/opand/Desktop/celebrating-config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - service-registry

  service-registry:
    build:
      context: ../service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - service-registry
      - auth-service
      - post-service
      - user-service
      - messaging-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - service-registry
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - service-registry
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  post-service:
    build:
      context: ../post-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - service-registry
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  messaging-service:
    build:
      context: ../messaging-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - service-registry
      - cassandra
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=celebrating_auth
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  mongo-data:
  cassandra-data: