spring:
  application:
    name: search-service
  config:
    import: "optional:configserver:http://localhost:8888"
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
  liquibase:
    url: jdbc:postgresql://localhost:5432/celebratedb
    user: celebrate
    password: celebrate123
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 